module.exports = {
  ORDER_STATUSES: [
    "RECEIVED", "CONFIRMED", "PREPARING", "READY",
    "PICKED_UP", "ON_THE_WAY", "DELIVERED", "CANCELLED", "REFUNDED"
  ],
  APPLICATION_STATUSES: [
    "NEW", "REVIEW", "INTERVIEW", "SHORTLISTED", "REJECTED", "HIRED"
  ]
};
