const db = require('../config/database');
const STATUS=['NEW','IN_PROGRESS','WAITING_CUSTOMER','RESOLVED','CLOSED'];
const CATEGORY=['ORDER','DELIVERY','PAYMENT','REFUND','TIOP_PLUS','ACCOUNT','RESTAURANT','OTHER'];
const REACTIONS=['👍','❤️','😂','😮','😢','🙏','🔥','✅'];
function cleanCategory(v){const map={commande:'ORDER',livraison:'DELIVERY',paiement:'PAYMENT',remboursement:'REFUND',tiopplus:'TIOP_PLUS',compte:'ACCOUNT',restaurant:'RESTAURANT',autre:'OTHER'};const c=map[String(v||'').toLowerCase()]||String(v||'').toUpperCase();return CATEGORY.includes(c)?c:'OTHER';}
exports.cleanCategory=cleanCategory; exports.statuses=STATUS; exports.reactions=REACTIONS;
exports.findOrderForUser=async(reference,userId)=>{if(!reference)return null;return (await db.query('SELECT id,reference FROM orders WHERE reference=? AND user_id=? LIMIT 1',[String(reference).trim(),userId]))[0]||null;};
async function addAttachments(conn,messageId,attachments=[]){for(const a of attachments){await conn.execute(`INSERT INTO support_message_attachments(message_id,original_name,stored_name,mime_type,file_size) VALUES(?,?,?,?,?)`,[messageId,a.originalName,a.storedName,a.mimeType,a.size]);}}
exports.createTicket=async({userId,orderId,subject,category,message,attachments=[]})=>{const c=await db.pool.getConnection();try{await c.beginTransaction();const [r]=await c.execute(`INSERT INTO support_tickets(reference,user_id,order_id,subject,category,priority,status) VALUES('',?,?,?,?, 'NORMAL','NEW')`,[userId,orderId||null,String(subject).slice(0,180),cleanCategory(category)]);const id=Number(r.insertId),reference=`SUP-${1000+id}`;await c.execute('UPDATE support_tickets SET reference=? WHERE id=?',[reference,id]);const [m]=await c.execute(`INSERT INTO support_messages(ticket_id,sender_type,sender_user_id,message) VALUES(?,'CUSTOMER',?,?)`,[id,userId,String(message||'').trim()]);await addAttachments(c,m.insertId,attachments);await c.commit();return{id,reference};}catch(e){await c.rollback();throw e;}finally{c.release();}};
const ticketBase=`SELECT t.*,u.email customer_email,COALESCE(NULLIF(up.display_name,''),NULLIF(CONCAT_WS(' ',up.first_name,up.last_name),''),u.email,CONCAT('Client #',u.id)) customer_name,o.reference order_reference,a.name assigned_admin_name,
 (SELECT sm.message FROM support_messages sm WHERE sm.ticket_id=t.id AND sm.deleted_at IS NULL ORDER BY sm.created_at DESC,sm.id DESC LIMIT 1) last_message,
 (SELECT sm.created_at FROM support_messages sm WHERE sm.ticket_id=t.id ORDER BY sm.created_at DESC,sm.id DESC LIMIT 1) last_message_at,
 (SELECT sm.sender_type FROM support_messages sm WHERE sm.ticket_id=t.id ORDER BY sm.created_at DESC,sm.id DESC LIMIT 1) last_sender_type,
 (SELECT COUNT(*) FROM support_message_attachments sma WHERE sma.message_id=(SELECT sm2.id FROM support_messages sm2 WHERE sm2.ticket_id=t.id AND sm2.deleted_at IS NULL ORDER BY sm2.created_at DESC,sm2.id DESC LIMIT 1)) last_attachment_count,
 (SELECT GROUP_CONCAT(r.emoji ORDER BY r.id SEPARATOR ' ') FROM support_message_reactions r WHERE r.message_id=(SELECT sm3.id FROM support_messages sm3 WHERE sm3.ticket_id=t.id AND sm3.deleted_at IS NULL ORDER BY sm3.created_at DESC,sm3.id DESC LIMIT 1)) last_reactions,
 (SELECT COUNT(*) FROM support_message_reactions r WHERE r.message_id=(SELECT sm4.id FROM support_messages sm4 WHERE sm4.ticket_id=t.id AND sm4.deleted_at IS NULL ORDER BY sm4.created_at DESC,sm4.id DESC LIMIT 1)) last_reaction_count`;
exports.listAdmin=async()=>db.query(`${ticketBase},(SELECT COUNT(*) FROM support_messages sm WHERE sm.ticket_id=t.id AND sm.sender_type='CUSTOMER' AND sm.read_at IS NULL AND sm.deleted_at IS NULL) unread_count FROM support_tickets t LEFT JOIN users u ON u.id=t.user_id LEFT JOIN user_profiles up ON up.user_id=u.id LEFT JOIN orders o ON o.id=t.order_id LEFT JOIN admin_users a ON a.id=t.assigned_admin_user_id ORDER BY COALESCE(last_message_at,t.updated_at) DESC,t.id DESC`);
exports.listForUser=async userId=>db.query(`${ticketBase},(SELECT COUNT(*) FROM support_messages sm WHERE sm.ticket_id=t.id AND sm.sender_type='ADMIN' AND sm.read_at IS NULL AND sm.deleted_at IS NULL) unread_count FROM support_tickets t LEFT JOIN users u ON u.id=t.user_id LEFT JOIN user_profiles up ON up.user_id=u.id LEFT JOIN orders o ON o.id=t.order_id LEFT JOIN admin_users a ON a.id=t.assigned_admin_user_id WHERE t.user_id=? AND t.client_archived_at IS NULL ORDER BY COALESCE(last_message_at,t.updated_at) DESC,t.id DESC`,[userId]);
exports.stats=async()=> (await db.query(`SELECT COUNT(*) total,SUM(status='NEW') new_count,SUM(status='IN_PROGRESS') in_progress_count,SUM(status='WAITING_CUSTOMER') waiting_count,SUM(status='RESOLVED') resolved_count,SUM(status='CLOSED') closed_count FROM support_tickets`))[0];
exports.findById=async id=>(await db.query('SELECT * FROM support_tickets WHERE id=? LIMIT 1',[id]))[0]||null;
exports.findForUser=async(id,userId)=>(await db.query(`SELECT t.*,o.reference order_reference FROM support_tickets t LEFT JOIN orders o ON o.id=t.order_id WHERE t.id=? AND t.user_id=? LIMIT 1`,[id,userId]))[0]||null;
exports.messages=async (ticketId,viewerType=null,viewerId=null)=>{const hidden=(viewerType&&viewerId)?` AND NOT EXISTS (SELECT 1 FROM support_message_hidden h WHERE h.message_id=sm.id AND h.actor_type=? AND h.actor_id=?)`:'';const params=(viewerType&&viewerId)?[ticketId,viewerType,Number(viewerId)]:[ticketId];const msgs=await db.query(`SELECT sm.*,COALESCE(a.name,COALESCE(NULLIF(up.display_name,''),CONCAT_WS(' ',up.first_name,up.last_name),u.email)) sender_name, rm.message reply_message,rm.sender_type reply_sender_type,rm.deleted_at reply_deleted_at,(SELECT COUNT(*) FROM support_message_attachments ra WHERE ra.message_id=rm.id) reply_attachment_count FROM support_messages sm LEFT JOIN support_messages rm ON rm.id=sm.reply_to_message_id LEFT JOIN admin_users a ON a.id=sm.sender_admin_user_id LEFT JOIN users u ON u.id=sm.sender_user_id LEFT JOIN user_profiles up ON up.user_id=u.id WHERE sm.ticket_id=?${hidden} ORDER BY sm.created_at,sm.id`,params);if(!msgs.length)return msgs;const ids=msgs.map(x=>x.id);const ph=ids.map(()=>'?').join(',');const at=await db.query(`SELECT * FROM support_message_attachments WHERE message_id IN (${ph}) ORDER BY id`,ids);const re=await db.query(`SELECT r.*,COALESCE(u.email,a.name) reactor_name FROM support_message_reactions r LEFT JOIN users u ON u.id=r.user_id LEFT JOIN admin_users a ON a.id=r.admin_user_id WHERE message_id IN (${ph}) ORDER BY r.id`,ids);for(const m of msgs){m.attachments=at.filter(x=>Number(x.message_id)===Number(m.id));if(m.attachment_url&&!m.attachments.length)m.attachments=[{id:0,original_name:'Pièce jointe',stored_name:String(m.attachment_url).split('/').pop(),mime_type:'',legacy_url:m.attachment_url}];m.reactions=re.filter(x=>Number(x.message_id)===Number(m.id));}return msgs;};
exports.markRead=async(ticketId,viewer,userId=null)=>{if(viewer==='CUSTOMER'){const t=await exports.findForUser(ticketId,userId);if(!t)return 0;const r=await db.query(`UPDATE support_messages SET read_at=COALESCE(read_at,NOW()) WHERE ticket_id=? AND sender_type='ADMIN' AND read_at IS NULL`,[ticketId]);return Number(r?.affectedRows||0);}const r=await db.query(`UPDATE support_messages SET read_at=COALESCE(read_at,NOW()) WHERE ticket_id=? AND sender_type='CUSTOMER' AND read_at IS NULL`,[ticketId]);return Number(r?.affectedRows||0);};
exports.markReadThrough=async(ticketId,viewer,messageId,userId=null)=>{ticketId=Number(ticketId);messageId=Number(messageId);if(!ticketId||!messageId)return 0;if(viewer==='CUSTOMER'){const t=await exports.findForUser(ticketId,userId);if(!t)return 0;const r=await db.query(`UPDATE support_messages SET read_at=COALESCE(read_at,NOW()) WHERE ticket_id=? AND sender_type='ADMIN' AND id<=? AND read_at IS NULL`,[ticketId,messageId]);return Number(r?.affectedRows||0);}const r=await db.query(`UPDATE support_messages SET read_at=COALESCE(read_at,NOW()) WHERE ticket_id=? AND sender_type='CUSTOMER' AND id<=? AND read_at IS NULL`,[ticketId,messageId]);return Number(r?.affectedRows||0);};
async function addMessage({ticketId,senderType,userId,adminId,text,attachments,status}){const c=await db.pool.getConnection();try{await c.beginTransaction();if(status)await c.execute('UPDATE support_tickets SET status=?,assigned_admin_user_id=COALESCE(assigned_admin_user_id,?),updated_at=NOW() WHERE id=?',[status,adminId||null,ticketId]);else await c.execute('UPDATE support_tickets SET updated_at=NOW() WHERE id=?',[ticketId]);const [m]=await c.execute(`INSERT INTO support_messages(ticket_id,sender_type,sender_user_id,sender_admin_user_id,message) VALUES(?,?,?,?,?)`,[ticketId,senderType,userId||null,adminId||null,text]);await addAttachments(c,m.insertId,attachments);await c.commit();return m.insertId;}catch(e){await c.rollback();throw e;}finally{c.release();}}
exports.replyCustomer=async({ticketId,userId,message,attachments=[],replyToMessageId=null})=>{const text=String(message||'').trim();if(!text&&!attachments.length)throw Object.assign(new Error('Votre message est vide.'),{statusCode:400});const c=await db.pool.getConnection();try{await c.beginTransaction();const [rows]=await c.execute('SELECT id,status FROM support_tickets WHERE id=? AND user_id=? FOR UPDATE',[ticketId,userId]);if(!rows.length)throw Object.assign(new Error('Ticket introuvable.'),{statusCode:404});if(rows[0].status==='CLOSED')throw Object.assign(new Error('Ce ticket est fermé.'),{statusCode:400});const [m]=await c.execute(`INSERT INTO support_messages(ticket_id,sender_type,sender_user_id,message,reply_to_message_id) VALUES(?,'CUSTOMER',?,?,?)`,[ticketId,userId,text,replyToMessageId||null]);await addAttachments(c,m.insertId,attachments);await c.execute(`UPDATE support_tickets SET status=CASE WHEN status IN ('RESOLVED','WAITING_CUSTOMER') THEN 'IN_PROGRESS' ELSE status END,updated_at=NOW() WHERE id=?`,[ticketId]);await c.commit();}catch(e){await c.rollback();throw e;}finally{c.release();}};
exports.replyAdmin=async({ticketId,adminId,status,message,attachments=[],replyToMessageId=null})=>{if(!STATUS.includes(status))throw new Error('Statut support invalide.');const t=await exports.findById(ticketId);if(!t)throw Object.assign(new Error('Ticket introuvable.'),{statusCode:404});const text=String(message||'').trim();if(text||attachments.length)await addMessage({ticketId,senderType:'ADMIN',adminId,text,attachments,status});else await db.query('UPDATE support_tickets SET status=?,assigned_admin_user_id=COALESCE(assigned_admin_user_id,?),updated_at=NOW() WHERE id=?',[status,adminId||null,ticketId]);};
exports.editMessage=async({messageId,ticketId,actorType,actorId,text})=>{text=String(text||'').trim();if(!text)throw Object.assign(new Error('Le message ne peut pas être vide.'),{statusCode:400});let sql=`UPDATE support_messages SET message=?,edited_at=NOW() WHERE id=? AND ticket_id=? AND deleted_at IS NULL AND sender_type=?`;const p=[text,messageId,ticketId,actorType];if(actorType==='CUSTOMER'){sql+=' AND sender_user_id=?';p.push(actorId);}else{sql+=' AND sender_admin_user_id=?';p.push(actorId);}const r=await db.query(sql,p);return r.affectedRows>0;};
exports.deleteMessage=async({messageId,ticketId,actorType,actorId})=>{let sql=`UPDATE support_messages SET message='',deleted_at=NOW(),edited_at=NOW() WHERE id=? AND ticket_id=? AND deleted_at IS NULL AND sender_type=?`;const p=[messageId,ticketId,actorType];if(actorType==='CUSTOMER'){sql+=' AND sender_user_id=?';p.push(actorId);}else{sql+=' AND sender_admin_user_id=?';p.push(actorId);}const r=await db.query(sql,p);return r.affectedRows>0;};
exports.react=async({messageId,ticketId,actorType,actorId,emoji})=>{if(!REACTIONS.includes(emoji))throw Object.assign(new Error('Réaction non autorisée.'),{statusCode:400});const m=(await db.query('SELECT id FROM support_messages WHERE id=? AND ticket_id=? AND deleted_at IS NULL LIMIT 1',[messageId,ticketId]))[0];if(!m)throw Object.assign(new Error('Message introuvable.'),{statusCode:404});if(actorType==='CUSTOMER'){await db.query(`INSERT INTO support_message_reactions(message_id,reactor_type,user_id,emoji) VALUES(?,'CUSTOMER',?,?) ON DUPLICATE KEY UPDATE emoji=VALUES(emoji),updated_at=NOW()`,[messageId,actorId,emoji]);}else{await db.query(`INSERT INTO support_message_reactions(message_id,reactor_type,admin_user_id,emoji) VALUES(?,'ADMIN',?,?) ON DUPLICATE KEY UPDATE emoji=VALUES(emoji),updated_at=NOW()`,[messageId,actorId,emoji]);}};

exports.archiveForUser=async(id,userId)=>{const r=await db.query('UPDATE support_tickets SET client_archived_at=NOW(),updated_at=NOW() WHERE id=? AND user_id=?',[id,userId]);return r.affectedRows>0;};
exports.archiveForAdmin=async id=>{const r=await db.query('UPDATE support_tickets SET admin_archived_at=NOW(),updated_at=NOW() WHERE id=?',[id]);return r.affectedRows>0;};
exports.attachmentForUser=async(attachmentId,userId)=>(await db.query(`SELECT a.* FROM support_message_attachments a JOIN support_messages m ON m.id=a.message_id JOIN support_tickets t ON t.id=m.ticket_id WHERE a.id=? AND t.user_id=? LIMIT 1`,[attachmentId,userId]))[0]||null;
exports.attachmentForAdmin=async attachmentId=>(await db.query(`SELECT a.* FROM support_message_attachments a JOIN support_messages m ON m.id=a.message_id WHERE a.id=? LIMIT 1`,[attachmentId]))[0]||null;

// ===== Support 18.6 : agents, priorites, filtres et conversation initiee par le support =====
const PRIORITIES=['LOW','NORMAL','HIGH','URGENT'];
exports.priorities=PRIORITIES;
exports.listAgents=async()=>db.query(`SELECT DISTINCT au.id,au.name,au.email,au.avatar_url,
 GROUP_CONCAT(DISTINCT r.name ORDER BY r.name SEPARATOR ', ') roles
 FROM admin_users au
 LEFT JOIN admin_user_roles aur ON aur.admin_user_id=au.id
 LEFT JOIN roles r ON r.id=aur.role_id
 WHERE au.is_active=1 AND (r.name IN ('SUPPORT','MANAGER','SUPER_ADMIN'))
 GROUP BY au.id,au.name,au.email,au.avatar_url ORDER BY au.name`);
exports.assignTicket=async({ticketId,adminId})=>{const id=adminId?Number(adminId):null;if(id){const ok=(await exports.listAgents()).some(a=>Number(a.id)===id);if(!ok)throw Object.assign(new Error('Agent support invalide ou inactif.'),{statusCode:400});}const r=await db.query('UPDATE support_tickets SET assigned_admin_user_id=?,updated_at=NOW() WHERE id=?',[id,Number(ticketId)]);return r.affectedRows>0;};
exports.setPriority=async({ticketId,priority})=>{priority=String(priority||'NORMAL').toUpperCase();if(!PRIORITIES.includes(priority))throw Object.assign(new Error('Priorité invalide.'),{statusCode:400});const r=await db.query('UPDATE support_tickets SET priority=?,updated_at=NOW() WHERE id=?',[priority,Number(ticketId)]);return r.affectedRows>0;};
exports.findOrderForAdmin=async reference=>(await db.query(`SELECT o.id,o.reference,o.user_id,COALESCE(NULLIF(up.display_name,''),NULLIF(CONCAT_WS(' ',up.first_name,up.last_name),''),u.email) customer_name,u.email customer_email FROM orders o JOIN users u ON u.id=o.user_id LEFT JOIN user_profiles up ON up.user_id=u.id WHERE o.reference=? AND o.user_id IS NOT NULL LIMIT 1`,[String(reference||'').trim()]))[0]||null;
exports.createAdminOrderConversation=async({orderReference,adminId,message,attachments=[]})=>{const order=await exports.findOrderForAdmin(orderReference);if(!order)throw Object.assign(new Error('Commande client introuvable ou sans compte client.'),{statusCode:404});const existing=(await db.query(`SELECT id,reference FROM support_tickets WHERE order_id=? AND user_id=? AND admin_archived_at IS NULL AND status<>'CLOSED' ORDER BY id DESC LIMIT 1`,[order.id,order.user_id]))[0];if(existing){const text=String(message||'').trim();if(text||attachments.length)await addMessage({ticketId:existing.id,senderType:'ADMIN',adminId,text,attachments,status:'IN_PROGRESS'});return{...existing,created:false,userId:order.user_id};}const c=await db.pool.getConnection();try{await c.beginTransaction();const subject=`Suivi de votre commande ${order.reference}`.slice(0,180);const [r]=await c.execute(`INSERT INTO support_tickets(reference,user_id,order_id,subject,category,priority,status,assigned_admin_user_id) VALUES('',?,?,?,'ORDER','NORMAL','IN_PROGRESS',?)`,[order.user_id,order.id,subject,adminId||null]);const id=Number(r.insertId),reference=`SUP-${1000+id}`;await c.execute('UPDATE support_tickets SET reference=? WHERE id=?',[reference,id]);const text=String(message||'').trim()||'Le support TiopTiop vous partage une mise à jour concernant la préparation de votre commande.';const [m]=await c.execute(`INSERT INTO support_messages(ticket_id,sender_type,sender_admin_user_id,message) VALUES(?,'ADMIN',?,?)`,[id,adminId||null,text]);await addAttachments(c,m.insertId,attachments);await c.commit();return{id,reference,created:true,userId:order.user_id};}catch(e){await c.rollback();throw e;}finally{c.release();}};


exports.validateReplyTarget=async(ticketId,messageId)=>{if(!messageId)return null;const r=(await db.query('SELECT id FROM support_messages WHERE id=? AND ticket_id=? LIMIT 1',[Number(messageId),Number(ticketId)]))[0];if(!r)throw Object.assign(new Error('Le message cité n’appartient pas à cette conversation.'),{statusCode:400});return Number(r.id);};

// ===== Support 18.7 : cycle de vie, reouverture et historique =====
const STATUS_TRANSITIONS={
 NEW:['NEW','IN_PROGRESS','CLOSED'],
 IN_PROGRESS:['IN_PROGRESS','WAITING_CUSTOMER','RESOLVED','CLOSED'],
 WAITING_CUSTOMER:['WAITING_CUSTOMER','IN_PROGRESS','RESOLVED','CLOSED'],
 RESOLVED:['RESOLVED','CLOSED'],
 CLOSED:['CLOSED']
};
exports.statusTransitions=STATUS_TRANSITIONS;
function assertTransition(from,to,{reopen=false}={}){
 from=String(from||'');to=String(to||'');
 if(!STATUS.includes(to))throw Object.assign(new Error('Statut support invalide.'),{statusCode:400});
 if(reopen&&['RESOLVED','CLOSED'].includes(from)&&to==='IN_PROGRESS')return;
 if(!(STATUS_TRANSITIONS[from]||[]).includes(to))throw Object.assign(new Error(`Transition ${from} → ${to} non autorisée.`),{statusCode:400});
}
async function logStatus(conn,{ticketId,fromStatus,toStatus,actorType,customerId=null,adminId=null,note=null}){
 if(fromStatus===toStatus)return;
 await conn.execute(`INSERT INTO support_ticket_status_history(ticket_id,from_status,to_status,actor_type,customer_user_id,admin_user_id,note) VALUES(?,?,?,?,?,?,?)`,[ticketId,fromStatus,toStatus,actorType,customerId,adminId,note]);
}
exports.statusHistory=async ticketId=>db.query(`SELECT h.*,COALESCE(a.name,COALESCE(NULLIF(up.display_name,''),CONCAT_WS(' ',up.first_name,up.last_name),u.email),'Système') actor_name FROM support_ticket_status_history h LEFT JOIN admin_users a ON a.id=h.admin_user_id LEFT JOIN users u ON u.id=h.customer_user_id LEFT JOIN user_profiles up ON up.user_id=u.id WHERE h.ticket_id=? ORDER BY h.created_at,h.id`,[ticketId]);
exports.replyAdmin=async({ticketId,adminId,status,message,attachments=[],replyToMessageId=null})=>{const text=String(message||'').trim();const c=await db.pool.getConnection();try{await c.beginTransaction();const [rows]=await c.execute('SELECT id,status FROM support_tickets WHERE id=? FOR UPDATE',[ticketId]);if(!rows.length)throw Object.assign(new Error('Ticket introuvable.'),{statusCode:404});const old=rows[0].status;assertTransition(old,status);if(text||attachments.length){const [m]=await c.execute(`INSERT INTO support_messages(ticket_id,sender_type,sender_admin_user_id,message,reply_to_message_id) VALUES(?,'ADMIN',?,?,?)`,[ticketId,adminId||null,text,replyToMessageId||null]);await addAttachments(c,m.insertId,attachments);}await c.execute('UPDATE support_tickets SET status=?,assigned_admin_user_id=COALESCE(assigned_admin_user_id,?),updated_at=NOW() WHERE id=?',[status,adminId||null,ticketId]);await logStatus(c,{ticketId,fromStatus:old,toStatus:status,actorType:'ADMIN',adminId:adminId||null});await c.commit();}catch(e){await c.rollback();throw e;}finally{c.release();}};
exports.replyCustomer=async({ticketId,userId,message,attachments=[],replyToMessageId=null})=>{const text=String(message||'').trim();if(!text&&!attachments.length)throw Object.assign(new Error('Votre message est vide.'),{statusCode:400});const c=await db.pool.getConnection();try{await c.beginTransaction();const [rows]=await c.execute('SELECT id,status FROM support_tickets WHERE id=? AND user_id=? FOR UPDATE',[ticketId,userId]);if(!rows.length)throw Object.assign(new Error('Ticket introuvable.'),{statusCode:404});const old=rows[0].status;if(['RESOLVED','CLOSED'].includes(old))throw Object.assign(new Error('Réouvrez cette demande avant de répondre.'),{statusCode:400});const next=old==='WAITING_CUSTOMER'?'IN_PROGRESS':old;const [m]=await c.execute(`INSERT INTO support_messages(ticket_id,sender_type,sender_user_id,message,reply_to_message_id) VALUES(?,'CUSTOMER',?,?,?)`,[ticketId,userId,text,replyToMessageId||null]);await addAttachments(c,m.insertId,attachments);await c.execute('UPDATE support_tickets SET status=?,updated_at=NOW() WHERE id=?',[next,ticketId]);await logStatus(c,{ticketId,fromStatus:old,toStatus:next,actorType:'CUSTOMER',customerId:userId,note:old==='WAITING_CUSTOMER'?'Réponse du client':null});await c.commit();}catch(e){await c.rollback();throw e;}finally{c.release();}};
exports.reopenForUser=async({ticketId,userId})=>{const c=await db.pool.getConnection();try{await c.beginTransaction();const [rows]=await c.execute('SELECT status FROM support_tickets WHERE id=? AND user_id=? FOR UPDATE',[ticketId,userId]);if(!rows.length)throw Object.assign(new Error('Demande introuvable.'),{statusCode:404});const old=rows[0].status;if(!['RESOLVED','CLOSED'].includes(old))throw Object.assign(new Error('Seule une demande résolue ou fermée peut être réouverte.'),{statusCode:400});assertTransition(old,'IN_PROGRESS',{reopen:true});await c.execute('UPDATE support_tickets SET status=\'IN_PROGRESS\',client_archived_at=NULL,updated_at=NOW() WHERE id=?',[ticketId]);await logStatus(c,{ticketId,fromStatus:old,toStatus:'IN_PROGRESS',actorType:'CUSTOMER',customerId:userId,note:'Demande réouverte par le client'});await c.commit();return true;}catch(e){await c.rollback();throw e;}finally{c.release();}};
exports.setStatusAdmin=async({ticketId,adminId,status})=>{const c=await db.pool.getConnection();try{await c.beginTransaction();const [rows]=await c.execute('SELECT status FROM support_tickets WHERE id=? FOR UPDATE',[ticketId]);if(!rows.length)throw Object.assign(new Error('Ticket introuvable.'),{statusCode:404});const old=rows[0].status;assertTransition(old,status);await c.execute('UPDATE support_tickets SET status=?,assigned_admin_user_id=COALESCE(assigned_admin_user_id,?),updated_at=NOW() WHERE id=?',[status,adminId||null,ticketId]);await logStatus(c,{ticketId,fromStatus:old,toStatus:status,actorType:'ADMIN',adminId:adminId||null,note:'Statut modifié par le support'});await c.commit();return{oldStatus:old,status};}catch(e){await c.rollback();throw e;}finally{c.release();}};
exports.reopenForAdmin=async({ticketId,adminId})=>{const c=await db.pool.getConnection();try{await c.beginTransaction();const [rows]=await c.execute('SELECT status FROM support_tickets WHERE id=? FOR UPDATE',[ticketId]);if(!rows.length)throw Object.assign(new Error('Ticket introuvable.'),{statusCode:404});const old=rows[0].status;if(!['RESOLVED','CLOSED'].includes(old))throw Object.assign(new Error('Seul un ticket résolu ou fermé peut être réouvert.'),{statusCode:400});assertTransition(old,'IN_PROGRESS',{reopen:true});await c.execute('UPDATE support_tickets SET status=\'IN_PROGRESS\',admin_archived_at=NULL,assigned_admin_user_id=COALESCE(assigned_admin_user_id,?),updated_at=NOW() WHERE id=?',[adminId||null,ticketId]);await logStatus(c,{ticketId,fromStatus:old,toStatus:'IN_PROGRESS',actorType:'ADMIN',adminId:adminId||null,note:'Ticket réouvert par le support'});await c.commit();return true;}catch(e){await c.rollback();throw e;}finally{c.release();}};


// ===== Support 18.7.2.4 : transfert sécurisé message / média =====
exports.transferMessage=async({sourceTicketId,targetTicketId,messageId=null,attachmentId=null,mode='media',actorType,actorId})=>{
 sourceTicketId=Number(sourceTicketId);targetTicketId=Number(targetTicketId);messageId=Number(messageId)||null;attachmentId=Number(attachmentId)||null;
 if(!sourceTicketId||!targetTicketId||sourceTicketId===targetTicketId)throw Object.assign(new Error('Choisissez une autre conversation.'),{statusCode:400});
 if(!['CUSTOMER','ADMIN'].includes(actorType))throw Object.assign(new Error('Acteur de transfert invalide.'),{statusCode:400});
 const c=await db.pool.getConnection();try{await c.beginTransaction();
  const [srcT]=await c.execute('SELECT id,user_id FROM support_tickets WHERE id=? LIMIT 1',[sourceTicketId]);
  const [dstT]=await c.execute('SELECT id,user_id,status FROM support_tickets WHERE id=? LIMIT 1',[targetTicketId]);
  if(!srcT.length||!dstT.length)throw Object.assign(new Error('Conversation introuvable.'),{statusCode:404});
  if(['RESOLVED','CLOSED'].includes(String(dstT[0].status)))throw Object.assign(new Error('Réouvrez la conversation destinataire avant le transfert.'),{statusCode:400});
  if(actorType==='CUSTOMER'&&(Number(srcT[0].user_id)!==Number(actorId)||Number(dstT[0].user_id)!==Number(actorId)))throw Object.assign(new Error('Transfert non autorisé.'),{statusCode:403});
  let srcMsg=null;
  if(messageId){const [r]=await c.execute('SELECT * FROM support_messages WHERE id=? AND ticket_id=? AND deleted_at IS NULL LIMIT 1',[messageId,sourceTicketId]);srcMsg=r[0]||null;}
  if(!srcMsg&&attachmentId){const [r]=await c.execute(`SELECT m.* FROM support_message_attachments a JOIN support_messages m ON m.id=a.message_id WHERE a.id=? AND m.ticket_id=? AND m.deleted_at IS NULL LIMIT 1`,[attachmentId,sourceTicketId]);srcMsg=r[0]||null;}
  if(!srcMsg)throw Object.assign(new Error('Message source introuvable.'),{statusCode:404});
  let files=[];
  if(mode==='message'){const [r]=await c.execute('SELECT original_name,stored_name,mime_type,file_size FROM support_message_attachments WHERE message_id=? ORDER BY id',[srcMsg.id]);files=r;}
  else{if(!attachmentId)throw Object.assign(new Error('Média source introuvable.'),{statusCode:400});const [r]=await c.execute('SELECT original_name,stored_name,mime_type,file_size FROM support_message_attachments WHERE id=? AND message_id=? LIMIT 1',[attachmentId,srcMsg.id]);files=r;if(!files.length)throw Object.assign(new Error('Média source introuvable.'),{statusCode:404});}
  const original=String(srcMsg.message||'').trim();const text=mode==='message'?(`↪ Transféré\n${original||'Message avec pièce jointe'}`):(`↪ Média transféré${original?' · '+original:''}`);
  const senderUser=actorType==='CUSTOMER'?Number(actorId):null,senderAdmin=actorType==='ADMIN'?Number(actorId):null;
  const [ins]=await c.execute('INSERT INTO support_messages(ticket_id,sender_type,sender_user_id,sender_admin_user_id,message) VALUES(?,?,?,?,?)',[targetTicketId,actorType,senderUser,senderAdmin,text.slice(0,4000)]);
  for(const a of files)await c.execute('INSERT INTO support_message_attachments(message_id,original_name,stored_name,mime_type,file_size) VALUES(?,?,?,?,?)',[ins.insertId,a.original_name,a.stored_name,a.mime_type,a.file_size]);
  let next=dstT[0].status;if(actorType==='CUSTOMER'&&next==='WAITING_CUSTOMER')next='IN_PROGRESS';
  await c.execute('UPDATE support_tickets SET status=?,updated_at=NOW() WHERE id=?',[next,targetTicketId]);
  await c.commit();return{messageId:Number(ins.insertId),targetTicketId,userId:Number(dstT[0].user_id),attachmentCount:files.length};
 }catch(e){await c.rollback();throw e;}finally{c.release();}
};


// ===== Support 18.7.2.4.1 : actions multiples temps réel =====
exports.bulkDeleteMessages=async({ticketId,messageIds=[],actorType,actorId,scope='everyone'})=>{
 const ids=[...new Set((messageIds||[]).map(Number).filter(Boolean))].slice(0,100);
 if(!ids.length)throw Object.assign(new Error('Sélection vide.'),{statusCode:400});
 const ph=ids.map(()=>'?').join(',');
 if(scope==='me'){const rows=await db.query(`SELECT id FROM support_messages WHERE ticket_id=? AND id IN (${ph})`,[Number(ticketId),...ids]);for(const row of rows){await db.query(`INSERT IGNORE INTO support_message_hidden(message_id,actor_type,actor_id) VALUES(?,?,?)`,[Number(row.id),actorType,Number(actorId)]);}return{deleted:rows.length,requested:ids.length,scope:'me'};}
 let sql=`UPDATE support_messages SET message='',deleted_at=NOW(),edited_at=NOW() WHERE ticket_id=? AND id IN (${ph}) AND deleted_at IS NULL AND sender_type=?`;
 const params=[Number(ticketId),...ids,actorType];
 if(actorType==='CUSTOMER'){sql+=' AND sender_user_id=?';params.push(Number(actorId));}else{sql+=' AND sender_admin_user_id=?';params.push(Number(actorId));}
 const r=await db.query(sql,params);return{deleted:Number(r.affectedRows||0),requested:ids.length,scope:'everyone'};
};
exports.bulkTransferMessages=async({sourceTicketId,targetTicketId,messageIds=[],actorType,actorId})=>{
 const ids=[...new Set((messageIds||[]).map(Number).filter(Boolean))].slice(0,50);
 if(!ids.length)throw Object.assign(new Error('Sélection vide.'),{statusCode:400});
 let count=0,attachments=0;
 for(const messageId of ids){const r=await exports.transferMessage({sourceTicketId,targetTicketId,messageId,mode:'message',actorType,actorId});count++;attachments+=Number(r.attachmentCount||0);}
 return{transferred:count,attachmentCount:attachments,targetTicketId:Number(targetTicketId)};
};
